REPORT_WHITELIST = [
    'KeywordPerformanceReport',
    'AdPerformanceReport',
    'AdGroupPerformanceReport',
    'GeographicPerformanceReport',
    'AgeGenderAudienceReport',
    'SearchQueryPerformanceReport',
    'CampaignPerformanceReport',
    'GoalsAndFunnelsReport',
    'AudiencePerformanceReport',
    'AdExtensionDetailReport'
]

REPORT_REQUIRED_FIELDS = ['_sdc_report_datetime', 'AccountId', 'TimePeriod']

REPORT_SPECIFIC_REQUIRED_FIELDS = {
    'GeographicPerformanceReport': ['AccountName'],
    'AgeGenderDemographicReport': [
        'AccountName',
        'AdGroupName',
        'AgeGroup',
        'Gender'
    ],
    'SearchQueryPerformanceReport': ['SearchQuery'],
    'AudiencePerformanceReport': ['AudienceId'],
    'AdExtensionDetailReport': [
        'AdExtensionId',
        'AdExtensionPropertyValue',
        'AdExtensionType',
        'AdExtensionTypeId' # removed `Impressions`, `Ctr,`, and `Clicks` from the required fields of `AdExtensionDetailReport`
    ],
    'GoalsAndFunnelsReport': ['Goal'],
    # added required fields for `AgeGenderAudienceReport` as mentioned in the bing-ads docs
    'AgeGenderAudienceReport': [
        'AccountName',
        'AdGroupName',
        'AgeGroup',
        'Gender'
    ],
}

## Any not listed here are strings
REPORTING_FIELD_TYPES = {
    'AccountId': 'integer',
    'AdId': 'integer',
    'AdGroupCriterionId': 'integer',
    'AdGroupId': 'integer',
    'AdRelevance': 'string',
    'Assists': 'integer',
    'AverageCpc': 'string',
    'AverageCpp': 'string',
    'AveragePosition': 'string',
    'BusinessCategoryId': 'integer',
    'BusinessListingId': 'integer',
    'CampaignId': 'integer',
    'ClickCalls': 'integer',
    'Clicks': 'integer',
    'ConversionRate': 'string',
    'Conversions': 'string',
    'CostPerAssist': 'string',
    'CostPerConversion': 'string',
    'Ctr': 'string',
    'CurrentMaxCpc': 'string',
    'EstimatedClickPercent': 'string',
    'EstimatedClicks': 'integer',
    'EstimatedConversionRate': 'string',
    'EstimatedConversions': 'integer',
    'EstimatedCtr': 'string',
    'EstimatedImpressionPercent': 'string',
    'EstimatedImpressions': 'integer',
    'ExactMatchImpressionSharePercent': 'string',
    'ExpectedCtr': 'string',
    'GoalId': 'integer',
    'HistoricAdRelevance':  'string',
    'HistoricExpectedCtr': 'string',
    'HistoricLandingPageExperience': 'string',
    'HistoricQualityScore': 'string',
    'ImpressionLostToAdRelevancePercent': 'string',
    'ImpressionLostToBidPercent': 'string',
    'ImpressionLostToBudgetPercent': 'string',
    'ImpressionLostToExpectedCtrPercent': 'string',
    'ImpressionLostToRankPercent': 'string',
    'Impressions': 'integer',
    'ImpressionSharePercent': 'string',
    'KeywordId': 'integer',
    'LandingPageExperience': 'string',
    'LocationId': 'integer',
    'LowQualityClicks': 'integer',
    'LowQualityClicksPercent': 'string',
    'LowQualityConversionRate': 'string',
    'LowQualityConversions': 'integer',
    'LowQualityGeneralClicks': 'integer',
    'LowQualityImpressions': 'integer',
    'LowQualityImpressionsPercent': 'string',
    'LowQualitySophisticatedClicks': 'integer',
    'Mainline1Bid': 'string',
    'MainlineBid': 'string',
    'ManualCalls': 'integer',
    'PhoneCalls': 'integer',
    'PhoneImpressions': 'integer',
    'Ptr': 'string',
    'QualityImpact': 'string',
    'QualityScore': 'string',
    'Radius': 'string',
    'ReturnOnAdSpend': 'string',
    'Revenue': 'string',
    'RevenuePerAssist': 'string',
    'RevenuePerConversion': 'string',
    'SidebarBid': 'string',
    'Spend': 'string',
    'TimePeriod': 'datetime'
}
